### ISSUE TITLE
Is this approach working with idp_version 3.3.2 ?

### ISSUE THREAD

**Issue by filak** [robertogallea/jaas_relational_login#1]
I have upgraded to IDP 3.3.2 (from 3.2.1) and the JAAS RDBMS login just stopped working. 
We use very similar "tagish" based code. Would you be so kind and confirm if your code works with IDP 3.3.2 ?

2018-04-06 22:41:04,934 - INFO [net.shibboleth.idp.authn.impl.ValidateUsernamePasswordAgainstJAAS:254] - [...] - [...] - Profile Action ValidateUsernamePasswordAgainstJAAS: Login by '...' via 'ShibUserPassAuth' failed
javax.security.auth.login.LoginException: Error reading user database (net.sourceforge.jtds.jdbc.Driver)
	at com.tagish.auth.DBLogin.validateUser(DBLogin.java:73)

**Comment by robertogallea** [comment]
I currently use IDP 3.3.2 and I haven't got any issue by using this approach. It seems like the problem is on the driver side. I never used jtds so I can't suggest you much. Please let me know if you have any issue or get stuck. 

P.S. I don't know how you get to this repo, but on http://www.robertogallea.com/blog/shibboleth_using_relational_dbms_as_authentication_backend you can find a guide related to this code.

**Comment by filak** [comment]
Thank you. It is working in IDP 3.3.2 indeed. But I had to put the JAR files (tagishauth.jar + jtds-1.3.1.jar) into the <IDP_HOME>\jetty-base\lib\ext\ folder - otherwise the libs would not get loaded (on Jetty 9.3.9) - not sure why.

**Comment by robertogallea** [comment]
Strange, it should not be required if you have already put those libraries into edit-webapp/WEB-INF/lib

Glad you manage to solve your issue.
